import { GlazeExpertColors } from "./GlazeExpertColors.js";
import { GlazePalettes } from "./GlazePalettes.js";

export const GlazeThemes = {
  // ---------------- Dashboard Themes ----------------
  dashboardLight: {
    name: "Dashboard Light",
    background: GlazePalettes.light[0],
    surface: GlazePalettes.light[3],
    primary: GlazeExpertColors.peterRiver,
    secondary: GlazeExpertColors.turquoise,
    accent: GlazeExpertColors.sunFlower,
    textPrimary: GlazeExpertColors.gray900,
    textSecondary: GlazeExpertColors.gray700,
    border: GlazeExpertColors.gray300,
    success: GlazeExpertColors.nephritis,
    warning: GlazeExpertColors.carrot,
    error: GlazeExpertColors.alizarin,
    info: GlazeExpertColors.belizeHole,
  },

  dashboardDark: {
    name: "Dashboard Dark",
    background: GlazePalettes.dark[0],
    surface: GlazePalettes.dark[3],
    primary: GlazeExpertColors.peterRiver,
    secondary: GlazeExpertColors.turquoise,
    accent: GlazeExpertColors.sunFlower,
    textPrimary: GlazeExpertColors.gray100,
    textSecondary: GlazeExpertColors.gray300,
    border: GlazeExpertColors.gray700,
    success: GlazeExpertColors.nephritis,
    warning: GlazeExpertColors.carrot,
    error: GlazeExpertColors.alizarin,
    info: GlazeExpertColors.belizeHole,
  },

  // ---------------- E-commerce Themes ----------------
  ecommerceLight: {
    name: "E-commerce Light",
    background: GlazeExpertColors.white,
    surface: GlazeExpertColors.clouds,
    primary: GlazeExpertColors.vibrantRed,
    secondary: GlazeExpertColors.vibrantBlue,
    accent: GlazeExpertColors.vibrantYellow,
    textPrimary: GlazeExpertColors.gray900,
    textSecondary: GlazeExpertColors.gray700,
    border: GlazeExpertColors.gray300,
    success: GlazeExpertColors.vibrantGreen,
    warning: GlazeExpertColors.vibrantOrange,
    error: GlazeExpertColors.vibrantRed,
    info: GlazeExpertColors.vibrantCyan,
  },

  ecommerceDark: {
    name: "E-commerce Dark",
    background: GlazePalettes.dark[0],
    surface: GlazePalettes.dark[3],
    primary: GlazeExpertColors.vibrantRed,
    secondary: GlazeExpertColors.vibrantBlue,
    accent: GlazeExpertColors.vibrantYellow,
    textPrimary: GlazeExpertColors.gray100,
    textSecondary: GlazeExpertColors.gray300,
    border: GlazeExpertColors.gray700,
    success: GlazeExpertColors.vibrantGreen,
    warning: GlazeExpertColors.vibrantOrange,
    error: GlazeExpertColors.vibrantRed,
    info: GlazeExpertColors.vibrantCyan,
  },

  // ---------------- Creative Themes ----------------
  creativeLight: {
    name: "Creative Light",
    background: GlazePalettes.pastel[0],
    surface: GlazePalettes.pastel[3],
    primary: GlazePalettes.vibrant[0],
    secondary: GlazePalettes.vibrant[3],
    accent: GlazeExpertColors.amethyst,
    textPrimary: GlazeExpertColors.gray900,
    textSecondary: GlazeExpertColors.gray700,
    border: GlazeExpertColors.gray300,
    success: GlazeExpertColors.nephritis,
    warning: GlazeExpertColors.carrot,
    error: GlazeExpertColors.alizarin,
    info: GlazeExpertColors.belizeHole,
  },

  creativeDark: {
    name: "Creative Dark",
    background: GlazePalettes.dark[0],
    surface: GlazePalettes.dark[3],
    primary: GlazePalettes.vibrant[0],
    secondary: GlazePalettes.vibrant[3],
    accent: GlazeExpertColors.amethyst,
    textPrimary: GlazeExpertColors.gray100,
    textSecondary: GlazeExpertColors.gray300,
    border: GlazeExpertColors.gray700,
    success: GlazeExpertColors.nephritis,
    warning: GlazeExpertColors.carrot,
    error: GlazeExpertColors.alizarin,
    info: GlazeExpertColors.belizeHole,
  },

  // ---------------- Corporate Themes ----------------
  corporateLight: {
    name: "Corporate Light",
    background: GlazeExpertColors.white,
    surface: GlazePalettes.light[3],
    primary: GlazeExpertColors.facebookBlue,
    secondary: GlazeExpertColors.linkedinBlue,
    accent: GlazeExpertColors.slackPurple,
    textPrimary: GlazeExpertColors.gray900,
    textSecondary: GlazeExpertColors.gray700,
    border: GlazeExpertColors.gray300,
    success: GlazeExpertColors.nephritis,
    warning: GlazeExpertColors.sunFlower,
    error: GlazeExpertColors.alizarin,
    info: GlazeExpertColors.belizeHole,
  },

  corporateDark: {
    name: "Corporate Dark",
    background: GlazePalettes.dark[0],
    surface: GlazePalettes.dark[3],
    primary: GlazeExpertColors.facebookBlue,
    secondary: GlazeExpertColors.linkedinBlue,
    accent: GlazeExpertColors.slackPurple,
    textPrimary: GlazeExpertColors.gray100,
    textSecondary: GlazeExpertColors.gray300,
    border: GlazeExpertColors.gray700,
    success: GlazeExpertColors.nephritis,
    warning: GlazeExpertColors.sunFlower,
    error: GlazeExpertColors.alizarin,
    info: GlazeExpertColors.belizeHole,
  },

  // ---------------- Accent Focused Themes ----------------
  vibrantFocus: {
    name: "Vibrant Focus",
    background: GlazePalettes.light[0],
    surface: GlazePalettes.light[2],
    primary: GlazeExpertColors.vibrantBlue,
    secondary: GlazeExpertColors.vibrantPink,
    accent: GlazeExpertColors.vibrantYellow,
    textPrimary: GlazeExpertColors.gray900,
    textSecondary: GlazeExpertColors.gray700,
    border: GlazeExpertColors.gray300,
    success: GlazeExpertColors.vibrantGreen,
    warning: GlazeExpertColors.vibrantOrange,
    error: GlazeExpertColors.vibrantRed,
    info: GlazeExpertColors.vibrantCyan,
  },

  pastelFocus: {
    name: "Pastel Focus",
    background: GlazePalettes.pastel[0],
    surface: GlazePalettes.pastel[3],
    primary: GlazePalettes.pastel[1],
    secondary: GlazePalettes.pastel[4],
    accent: GlazePalettes.pastel[7],
    textPrimary: GlazeExpertColors.gray900,
    textSecondary: GlazeExpertColors.gray700,
    border: GlazeExpertColors.gray300,
    success: GlazeExpertColors.nephritis,
    warning: GlazeExpertColors.carrot,
    error: GlazeExpertColors.alizarin,
    info: GlazeExpertColors.belizeHole,
  },
};
